baseURL = "https://keyooooo.github.io/blog/"
defaultContentLanguage = "zh-cn"
title = "Nomad's Blog"
theme = "PaperMod"

[taxonomies]
tag = "tags"
category = "categories"

[[menu.main]]
identifier = "posts"
name = "文章"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "about"
name = "关于我"
url = "/about/"
weight = 40

[[menu.main]]
identifier = "links"
name = "友链"
url = "/links/"
weight = 50

[params]
ShowReadingTime = true
ShowCodeCopyButtons = true
ShowBreadCrumbs = true
ShowToc = true